services:
  - type: web
    name: your-fe-name
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
